### ISSUE TITLE
V2v1: V2.2 Precio real (13ptos)

### ISSUE THREAD

**Issue by bandresJar** [2019-a-gr2-web/ProyectoFinal-Grupo1#14]
En caso   que haga compras de nuevos productos | cuando se   ingresen al inventario | el sistema debe   permitir llevar un control de sus costos y precio real para calcular   ganancias.
-- | -- | --

**Comment by Leon2308** [comment]
Se sugiere agregar etiquetas de prioridad y módulos para comprender mejor.
