### ISSUE TITLE
V3v1 Vendedor parte 3

### ISSUE THREAD

**Issue by bandresJar** [2019-a-gr2-web/ProyectoFinal-Grupo1#15]
Como   un vendedor | Necesito llevar un   registro de ventas por usuarios y estadisticas de los productos | Con la finalidad   de  automatizar el proceso de toma de   deciciones, compras y promociones.  | Se validara V3.1 y V3.2
-- | -- | --

**Comment by Leon2308** [comment]
Corregir el formato de la historia de usuario.
