### ISSUE TITLE
V3v1: V3.2 Promociones hasta en Precio real (13ptos)

### ISSUE THREAD

**Issue by bandresJar** [2019-a-gr2-web/ProyectoFinal-Grupo1#18]
En caso   que los clientes formen parte de las estadisticas | cuando este haga   compras | el sistema debe   permitir enviar una prpaganda personalizada con alguna promocion para el   cliente con hasta un precio minimo del precio real.
-- | -- | --

**Comment by Leon2308** [comment]
error de tipeo "prpaganda"
