### ISSUE TITLE
Iiv1: I1.1Permitir visualizar (1pto)

### ISSUE THREAD

**Issue by bandresJar** [2019-a-gr2-web/ProyectoFinal-Grupo1#19]
En caso   que necesite realizar una compra | cuando haya   descargado la aplicación o en cualquier pantalla | el sistema debe   pemitir la navegacion por la aplicación sin funciones de pagos o entrega
-- | -- | --

**Comment by Leon2308** [comment]
Aplicar el mismo formato de las historias de usuario iniciales.
